coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 70%
        threshold: 5%
ignore:
  - "src/main/java/seedu/address/ui/
